title: muriloviana.me
description: Personal blog to share some thoughts, knowledge and experiences.
url: https://muriloviana.me

remote_theme: jekyll/minima
permalink: /posts/:slug/
timezone: America/SaoPaulo
markdown: kramdown

# Disqus
disqus:
    shortname: https-muriloviana-me

# Social media
minima:
  social_links:
    twitter: murilovmo
    github: muriloviana
    linkedin: muriloviana

# Pagination
paginate: 5
paginate_path: /page/:num/
