title: muriloviana.me
description: Blog pessoal para compartilhar aprendizados, conhecimentos e pensamentos
url: https://muriloviana.me

remote_theme: jekyll/minima
permalink: /posts/:slug/
timezone: America/SaoPaulo
markdown: kramdown

# Google Analytics
google_analytics: G-EVQJBVSCW5

# Social media
minima:
  skin: dark
  social_links:
    github: muriloviana
    instagram: muuviana
    linkedin: muriloviana
    twitter: muuviana

# Pagination
paginate: 5
paginate_path: /page/:num/
